baseURL: https://example.com
languageCode: en-us
title: SPP 608
theme: vanilla-bootstrap-hugo-theme
googleAnalytics: UA-123456789-1

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Overview
    pre: edit
    url: /overview/
    weight: 2
  - name: Schedule
    pre: tag
    url: /tags/
    weight: 3
  - name: Policies
    pre: smile
    url: /policies/
    weight: 4
  - name: R Studio
    pre: rss
    url: 'https://rstudio.cloud/'
    weight: 5    
  - name: Gradescope
    pre: rss
    url: 'https://www.gradescope.com/'
    weight: 6
  - name: Moodle
    pre: moodle_logo
    url: 'https://moodle.umass.edu/'
    weight: 7

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream.
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
